In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
import time

In [10]:
a = np.random.rand(1000000) #million dim array
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)

toc = time.time()
print("Vectorized version: " + str(1000*(toc-tic)) + " ms")

Vectorized version: 1.0769367218017578 ms


In [11]:
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)

print("For loop: " + str(1000*(toc-tic)) + " ms")

249902.880649896
For loop: 214.87188339233398 ms


## Broadcasting Example

In [4]:
A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [16]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [17]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [15]:
percentage = 100*A/cal.reshape(1,4)
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])

In [19]:
a = np.random.randn(5)   #creates 5 random gaussian variables

In [21]:
a.shape   #rank 1 array, not good when programming a neural network

(5,)

## Vectorizing Logistic Regression